//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WindowsFormsApp1.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        internal readonly string LOGDIR_PATH = "./logs/";
        internal readonly string LOGFILE_NAME = "consoleerrormessage";
        internal readonly int LOG_LEVEL = 3;
        internal readonly long LOGFILE_MAXSIZE = 10485760;
        internal readonly int LOGFILE_PERIOD = 30;

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
